### ISSUE TITLE
Update http package dependency

### ISSUE THREAD

**Issue by TheManuz** [appsup-dart/openid_client#103]
As I'm writing, `openid_client` depends on `http` package `^0.13.0`, but it can updated to `^1.1.0`.

This dependency blocks me from upgrading other packages that dependes on `http`.

Could you update your dependencies?

Thanks

**Comment by rbellens** [comment]
The dependency is `http: ">=0.13.5 <2.0.0"`, so it already supports version `1.1.0`. Maybe you are on an older version or you should run `dart pub upgrade`.

**Comment by TheManuz** [comment]
I understand what you're saying, but I'm getting this error when trying to update `flutter_map` dependency, somehow the dependencies are conflicting.

```zsh
Resolving dependencies...
Because openid_client 0.4.7 depends on http ^0.13.0 and flutter_map >=5.0.0 depends on http ^1.0.0, openid_client 0.4.7 is incompatible with flutter_map >=5.0.0.
So, because droppay_frontend_application depends on both flutter_map 6.0.1 and openid_client 0.4.7, version solving failed.
```

**Comment by rbellens** [comment]
Yes, version `0.4.7` had a dependency on http `^0.13.0`, but there is a new version since about two weeks with an updated dependency. So apparently you haven't upgraded the version of openid_client to 0.4.8

**Comment by TheManuz** [comment]
I totally missed version `0.4.8`, and it fixes dependency like you said!

Sorry for missing it, and thank you very much for your help!
