### ISSUE TITLE
URL returns as ************************* in android 13 devices

### ISSUE THREAD

**Issue by jefrisingh** [appsup-dart/openid_client#111]
The sample code 

`authenticate(Uri uri, String clientId, List<String> scopes) async {   
    
    // create the client
    var issuer = await Issuer.discover(uri);
    var client = new Client(issuer, clientId);
    
    // create a function to open a browser with an url
    urlLauncher(String url) async {
        if (await canLaunch(url)) {
          await launch(url, forceWebView: true);
        } else {
          throw 'Could not launch $url';
        }
    }
    
    // create an authenticator
    var authenticator = new Authenticator(client,
        scopes: scopes,
        port: 4000, urlLancher: urlLauncher);
    
    // starts the authentication
    var c = await authenticator.authorize();
    
    // close the webview when finished
    closeWebView();
    
    // return the user info
    return await c.getUserInfo();

}`

Is working fine on android 8 and 10 devices but If I run the same application in android 13 device, It is returing the following error

Could not launch ****************************************************************************************************************

After loging the URL i came to know on android 8 and 10 I receive proper url inside the Authenticator urlLauncher but I receive ********************************************************** as the url in android 13 devices.

**Comment by Briandosha** [comment]
hi am facing a similar issue did you get any solution?

**Comment by jefrisingh** [comment]
Please go to https://pub.dev/packages/url_launcher

and in readme look for configuration -> Android which is very importent, I was missed that, after adding it everything is working as expected, It is not bug of openid_client.

**Comment by Briandosha** [comment]
Thank you very much it works
