### ISSUE TITLE
Dart 3.5

### ISSUE THREAD

**Issue by nev-21** [appsup-dart/openid_client#119]
Hi, it is possible to use this library with Dart 3.5?

**Comment by nev-21** [comment]
I'm confused, pub.dev says it is dart 3 compatible (tested with dart 3.5).

But your pubspec.yaml says 
sdk: '>=2.12.0 <3.0.0'

**Comment by rbellens** [comment]
when running dart 3 sdk, the constraint `sdk: '>=2.12.0 <3.0.0'` is interpreted as `sdk: '>=2.12.0 <4.0.0'`

see the official docs: https://dart.dev/resources/dart-3-migration#dart-3-backwards-compatibility

**Comment by Tristan-gu** [comment]
> when running dart 3 sdk, the constraint `sdk: '>=2.12.0 <3.0.0'` is interpreted as `sdk: '>=2.12.0 <4.0.0'`
> 
> see the official docs: https://dart.dev/resources/dart-3-migration#dart-3-backwards-compatibility

Thank you for your answer.
But, is there any reason to keep `sdk: '>=2.12.0 <3.0.0' instead of '>=2.12.0 <4.0.0' ?

To avoid any confusion.
