### ISSUE TITLE
Authenticator Logout does not seem to be supported.

### ISSUE THREAD

**Issue by JasonSheedy** [appsup-dart/openid_client#15]
Hi,
I'm using your library in a new Flutter app and so far it's working very nicely. Nice work. I'm trying to implement logout, but it doesn't seem to be implemented on the Authenticator class as suggested in your example. I'm on v0.2.5. Can you offer any advice? Thanks

https://github.com/appsup-dart/openid_client/blob/4e3b944137a620ff63a47194a8f079e86f59556c/example/main.dart#L91

**Comment by ldemyanenko** [comment]
I'm having the same issue. Looks like there is no way for correct logout

**Comment by canberkardic** [comment]
Same problem here.

**Comment by XMrGX** [comment]
I'm with the same problem, have another way to do logout without the default method?

**Comment by ldemyanenko** [comment]
The main problem appears when you trying to make several logins on one app session.  On the second and next logins of the same session web view automatically authenticate the user as first login credentials user.

**Comment by ldemyanenko** [comment]
Solution that worked for me was direct call of openid logout endpoint 
http://{domain-name}/auth/realms/{realm-name}/protocol/openid-connect/logout?redirect_uri=encodedRedirectUr

**Comment by rbellens** [comment]
This is now supported in version `0.3.0`

**Comment by JasonSheedy** [comment]
Hi rbellens,
Thanks for the update. Unfortunately, this has only been implemented in `openid_client_browser.dart` and is not implemented in `openid_client_io.dart`. I have implemented it manually in a flutter app I'm working on, but it would be better if the Authenticator API was consistent between implementations ..

**Comment by edihasaj** [comment]
> 
> 
> Hi rbellens,
> Thanks for the update. Unfortunately, this has only been implemented in `openid_client_browser.dart` and is not implemented in `openid_client_io.dart`. I have implemented it manually in a flutter app I'm working on, but it would be better if the Authenticator API was consistent between implementations ..

Hey @JasonSheedy,
Can you share the code part how you implemeted it?

**Comment by JasonSheedy** [comment]
> > Hi rbellens,
> > Thanks for the update. Unfortunately, this has only been implemented in `openid_client_browser.dart` and is not implemented in `openid_client_io.dart`. I have implemented it manually in a flutter app I'm working on, but it would be better if the Authenticator API was consistent between implementations ..
> 
> Hey @JasonSheedy,
> Can you share the code part how you implemeted it?

Hi edi,
It was just a matter of launching the logout URL manually and handling the redirect intent via a channel listener. Something like this:

`Future<void> logout() async {
    log.i('Executing logout.');
    _addLogoutListener();

    HttpUtil.launchUrl('INSERT LOGOUT URL HERE');
  }

  void _addLogoutListener() {
    CHANNEL.setMethodCallHandler(_logoutHandler);
  }

Future<void> _logoutHandler(MethodCall call) async {
    final args = call.arguments;
    if(call.method == 'onAuthResponse') {
      log.d('Received logout response $args');
      CHANNEL.setMethodCallHandler((call) => null);
    }
  }`

**Comment by xmartinez22** [comment]
using the logout url does not work. I'm trying to sign in under a different name and it just signs in automatically after signing out. 

using logout endsession

**Comment by SameerChorge94** [comment]
any solution or workaround on this issues yet ??
facing same issue calling external logout post request doesn't work for me 
getting the below error 
`{error: unauthorized_client, error_description: INVALID_CREDENTIALS: Invalid client credentials}
`

i send the access_token in headers with below request body contents 
```
{
          "client_id": <client_id>,
          "refresh_token": <refresh_token>,
        }
```

**Comment by SameerChorge94** [comment]
> any solution or workaround on this issues yet ?? facing same issue calling external logout post request doesn't work for me getting the below error `{error: unauthorized_client, error_description: INVALID_CREDENTIALS: Invalid client credentials} `
> 
> i send the access_token in headers with below request body contents
> 
> ```
> {
>           "client_id": <client_id>,
>           "refresh_token": <refresh_token>,
>         }
> ```

i'm able to logout from the mobile devices by calling the post requset to keycloak for logout 
after the success response from below post API response i clear the local sessions variables 
```
var logoutRes = await http.post(
          Uri.parse(
              '<KEYCLOAK_HOST_URL>/auth/realms/<KEYCLOAK_REALM>/protocol/openid-connect/logout'),
          headers: {"Content-type": "application/x-www-form-urlencoded"},
          body: {
            "grant_type": "refresh_token",
            "client_id": "<KEYCLOAK_CLIENT_ID>",
            "refresh_token":" <REFRESH_TOKEN>"
          },
        );
```

**Comment by FrankDupree** [comment]
> using the logout url does not work. I'm trying to sign in under a different name and it just signs in automatically after signing out.
> 
> using logout endsession

@xmartinez22 were you able to resolve this, I also want to sign in a different user
