### ISSUE TITLE
ERR_CLEARTEXT_NOT_PERMITTED Android

### ISSUE THREAD

**Issue by jhancock4d** [appsup-dart/openid_client#16]
Using the default redirect url on port 4000 per the example on android results with the above error message.

It would be much better if this library used the device's authentication system to get notifications back of the authentication. And on web just redirected and picked it up from the url.

Otherwise It appears that at least on Android https is required.

**Comment by MarcusSchilling** [comment]
Same problem

**Comment by canberkardic** [comment]
Open android manifest file which is located at  android/app/src/main/AndroidManifest.xml and add 
``android:usesCleartextTraffic="true"`` to the application tag.
This will like below;
``
<application  
    android:name="io.flutter.app.FlutterApplication"  
    android:label="tangerine_ui"  
    android:icon="@mipmap/ic_launcher"  
    android:usesCleartextTraffic="true">
``

**Comment by MarcusSchilling** [comment]
Thank you 👍
