### ISSUE TITLE
Not able to retrieve the Access token and Refresh token after successful redirection from keyCloak to the App (Flutter Web)

### ISSUE THREAD

**Issue by ptawde95** [appsup-dart/openid_client#19]
Description :

Redirection to Keycloak is working properly but even after successful authentication from Keycloak not able to retrieve the Access token and Refresh token.

Expected Results :  

After Successful redirection from  Keycloak, it should store the access token and refresh token in local storage or cache
eg:- It should at least store the access token or response  in window.localStorage['openid_client:auth']

Actual Result : Currently only the state is stored in the local storage in window.localStorage['openid_client:state']
and the window.localStorage['openid_client:auth'] is empty, not able to retrieve the access token or the refresh token from the local storage of the browser

**Comment by sarat12us** [comment]
Did you find any resolution for this?

**Comment by gibahjoe** [comment]
I think the web implementation is incomplete. I am also experiencing this. does anyone have a workaround?

**Comment by ronymesquita** [comment]
Depending on the version used, Keycloak disables refresh token by default. This can be enabled in `client` configuration going to the `OpenID Connect Compatibility Modes`.
The image below shows and example of configuraiton in Keycloak 12.

![Screenshot_2021-01-13 Keycloak Admin Console](https://user-images.githubusercontent.com/41541500/104457183-74e4d880-5588-11eb-8e3e-377e92dd55b5.png)

I hope this helps. :+1:

**Comment by talbiislam96** [comment]
Can you please share the whole code , am also using openId package in flutter to redirect my app to keycloak server to authenticate the user then redirect them from keycloak to the app again .However it doesn't seem to be working for me and i have no idea how to fix it . This is the function am using :
`

authenticate() async {

    const DOMAIN = 'http://10.0.2.2:8080/auth/realms/clients';
    const CLIENT_ID = 'helium-mobile';

    const REDIRECT_URI = 'com.example.helium_app://login-callback';
    const AUTH0_ISSUER = 'https://$DOMAIN';




    var uri = Uri.parse('http://10.0.2.2:8080/auth/realms/clients');
    var clientId = 'helium-mobile';
    var scopes = List<String>.of(['openid', 'profile']);
    var port = 4200;
    var redirectUri = Uri.parse('http://localhost:4200');

    var issuer = await Issuer.discover(uri);
    var client = new Client(issuer, clientId);

    urlLauncher(String url) async {
      if (await canLaunch(url)) {
        await launch(url, forceWebView: true);
      } else {
        throw 'Could not launch $url';
      }
    }

    var authenticator = new Authenticator(client,
      scopes: scopes,
      port: port,
      urlLancher: urlLauncher,);

    var c = await authenticator.authorize();
    closeWebView();

    var token= await c.getTokenResponse();
    print(token);
    return token;
  }

`


i got this trace stack : 

`

E/flutter ( 8782): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Instance of 'HttpRequestException'
E/flutter ( 8782): #0      _processResponse (package:openid_client/src/http_util.dart:37:5)
E/flutter ( 8782): #1      get (package:openid_client/src/http_util.dart:18:10)
E/flutter ( 8782): <asynchronous suspension>
E/flutter ( 8782): #2      Issuer.discover (package:openid_client/src/openid.dart:124:16)
E/flutter ( 8782): <asynchronous suspension>
E/flutter ( 8782): #3      Body.authenticate (package:helium_app/screens/login/components/body.dart:50:18)
E/flutter ( 8782): <asynchronous suspension>
E/flutter ( 8782): 





`
if anyone know how to fix this please give me some feedback , i'd be grateful

**Comment by ronymesquita** [comment]
I have put and example at https://github.com/ronymesquita/flutter-and-keycloak. It uses Keycloak to authenticate and Flutter mobile as the client.
The [oauth2](https://pub.dev/packages/oauth2) package has instructions on how tho make the authentication. My example is based on the [Authorization Code Grant](https://pub.dev/packages/oauth2#authorization-code-grant) section.

**Comment by SylvainAssemat** [comment]
@talbiislam96 

I just met the same issue today
My fix was to add the client Secret 

`var client = new Client(issuer, clientId, **clientSecret: "xxxxxxxxxxxxxxxxxxxxxxxxx"**); `

Can you have a try and reproduce ?

**Comment by rbellens** [comment]
There are now some working examples for different platforms in the example directory that use keycloak. Please, check them out if you still experience this issue.

**Comment by rbellens** [comment]
When you use the Authenticator in `openid_client_browser.dart`, the implicit flow will be used. This flow generally does not return a refresh token, so it is not possible to refresh through the getTokenResponse method. You could try `trySilentRefresh`, which uses an iframe to refresh the token. Or use another flow, in which case you will not be able to use the Authenticator class  in `openid_client_browser.dart`, but should implement something similar.
