### ISSUE TITLE
Flutter Support 

### ISSUE THREAD

**Issue by tolstenko** [appsup-dart/openid_client#2]
Please support Flutter.

Steps to reproduce error:
I put "openid_client: ^0.1.3" in the file pubspec.yaml dependencies. But it depends on "unscripted" and it depends on 'dart:mirrors', which is incompatible with flutter.

**Comment by rbellens** [comment]
openid_client depends on some libraries that do not support flutter (yet). I am investigating how to overcome these issues, but it might take some more time.

**Comment by samgithub-duplicate** [comment]
Hi Jeremy:
Did you find a solution yet?  I am caught in the same roadblock.

Sam

**Comment by Jeremywhiteley** [comment]
Yes!  I am using this solution that was just published.  It's pretty slick.   
https://pub.dartlang.org/packages/simple_auth_flutter

**Comment by rbellens** [comment]
Latest version of the package `0.2.1` supports both web and flutter. 
Closing this issue now.

**Comment by rbellens** [comment]
See also https://github.com/appsup-dart/openid_flutter_example for example usage on flutter
