### ISSUE TITLE
Dynamic OpenID Providers MUST support the code, id_token, and the token id_token Response Type values.

### ISSUE THREAD

**Issue by mingxun** [appsup-dart/openid_client#20]
According to this openID document https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationResponse, "Dynamic OpenID Providers MUST support the code, id_token, and the token id_token Response Type values.". I tried using openID_client to connect with login.gov. login.gov's discovery metadata has   "response_types_supported": ["code"],  openid_client will fail at this function:

Flow.implicit(Client client, {String state})
      : this._(
            FlowType.implicit,
            ['token id_token', 'id_token token', 'id_token', 'token']
                .firstWhere((v) =>
                    client.issuer.metadata.responseTypesSupported.contains(v)),
            client,
            state: state);

Can we add 'Code' in the list?

**Comment by rbellens** [comment]
I believe the `code` is used for authorization code flow not for the implicit flow. So, you should use the `Flow.authorizationCodeWithPKCE` or `Flow.authorizationCode` instead.
