### ISSUE TITLE
authorize won't return Valid credential obj

### ISSUE THREAD

**Issue by sarat12us** [appsup-dart/openid_client#26]
In Web integration with AutherizationPKCE authorize won't return Valid credential obj
Not able to get Refresh Token , access Token, ID token

**Comment by cactysman** [comment]
Experiencing this too.
The URL Hash is there and localStorage also contains the required values but `authenticator.credential` still yields `null`.

Using version `0.3.1` with flutter `1.24.0-10.2.pre`.

**Comment by Memo99** [comment]
Same problem here, any solution? Only state is stored in local_storage and credentials is empty. Also do i have to handle the weird redirect with custom route? This is the first big blocking point on flutter for me. 

Using keycloak.

**Comment by SameerChorge94** [comment]
Any update on this issue ?
Facing same issue using the keycloak

**Comment by rbellens** [comment]
Have a look at the flutter example in the example directory.
