### ISSUE TITLE
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found

### ISSUE THREAD

**Issue by karezza** [appsup-dart/openid_client#30]
I have installed the needed CA to the android phone yet still getting the above error.  Could it be what is causing me to get a blank white screen?

Also, assuming the white screen is a failed attempt to collect my credentials.  I already have the credentials, could I possibly pass those in?

I/cr_X509Util(24485): Failed to validate the certificate chain, error: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
E/chromium(24485): [ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -202

**Comment by BryanStackpole** [comment]
Same issue.

**Comment by everystone** [comment]
Same issue here as well. @karezza or @BryanStackpole  did you figure this out?

**Comment by rbellens** [comment]
Don't think this is an issue with this library. The error is thrown from java(android) code.
