### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by innovativeAfrica** [appsup-dart/openid_client#37]
Hi everyone. I use the openid_client library in flutter mobile app with keycloak server. But access token returned after login is invalid.Please someone can help me. Thanks

My flutter login code:
` login() async {

    var uri = Uri.parse(env["KEYCLOAKURL"].toString());
     var clientId = env["KEYCLOAKCLIENTID"].toString();
     var scopes = List<String>.of(['openid', 'profile', 'offline_access']);
     var issuer = await Issuer.discover(uri);
     var client = new Client(issuer, clientId);
     urlLauncher(String url) async {
       if (await canLaunch(url)) {
              await launch(url);
              } else {
                   throw 'Could not launch $url';
                 }
       }
    var authenticator = new Authenticator(client,
        scopes: scopes, port: 8080, urlLancher: urlLauncher);

    var c = await authenticator.authorize();

    TokenResponse tokenResponse = await c.getTokenResponse();
    await this.storage.write(key: "REFRESH", value: tokenResponse.refreshToken);
    await this.storage.write(key: "TOKEN", value: tokenResponse.accessToken);

    closeWebView();

  }`
Keycloak configuration:

![Capture](https://user-images.githubusercontent.com/61746950/113362262-e17ca180-9345-11eb-86dd-c56b381ea1ae.PNG)

**Comment by rbellens** [comment]
There is now a flutter example with a keycloak server in the examples directory. Please, check it out.
