### ISSUE TITLE
getUserInfo type cast error

### ISSUE THREAD

**Issue by indiealexh** [appsup-dart/openid_client#38]
Dart version: 2.12.2

After authenticating and attempting to obtain the user info using the `getUserInfo()` method the following error occurs:

```
E/flutter ( 6893): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: type 'Future<dynamic>' is not a subtype of type 'FutureOr<Map<String, dynamic>>' in type cast
E/flutter ( 6893): #0      Credential.getUserInfo (package:openid_client/src/openid.dart:195:26)
```

If I modify the line 
`return UserInfo.fromJson(await (_get(uri) as FutureOr<Map<String, dynamic>>));`
to
`return UserInfo.fromJson(await (_get(uri)));`

The error goes away and everything works as expected, not sure that this would be the best approach though.

Ideas on a fix? Happy to PR it after discussion.

**Comment by rbellens** [comment]
This `as` statement was introduced by the null-safety migration tool, but it should not be there. I've fixed it and will release soon.
