### ISSUE TITLE
App stays in pause state

### ISSUE THREAD

**Issue by vaggelis2018** [appsup-dart/openid_client#39]
Hello, 

I have implemented a  PCKE  flow by redirecting the user to identity provider and everything works fine. The problem I have is that if the user click back button of his phone in the webview instead of adding his credentials and log in, he returns to app but the app remains in pause state. I tried to find if the  url launcher gets any parameter as a back button callback but I was not able to find something.  Do I miss something?

**Comment by j0k3r96** [comment]
Hey,
@vaggelis2018  I have the same problem. Did you find a workaround?

**Comment by vaggelis2018** [comment]
I manually continue the app. I was not able to find another solution man

**Comment by dawid-niedzwiecki** [comment]
> I manually continue the app. I was not able to find another solution man

How did you achieve this

**Comment by rbellens** [comment]
You should probably call the `cancel` method of the Authenticator, when the user cancels the flow by pressing the back button.
