### ISSUE TITLE
Expired access token in openid_client:auth causes getUserInfo to fail

### ISSUE THREAD

**Issue by ntoljic** [appsup-dart/openid_client#40]
I have a working authentication setup for web, i.e. I open the app, I get redirected, insert my credentials, get redirected again and get a valid result from `getUserInfo`.
However when I reopen the app after the originally issued access token has expired, the process fails. The auth server (keycloak in this case) returns:
```
www-authenticate: Bearer realm="MyRealm", error="invalid_token", error_description="Token verification failed"
```
Analyzing the request that gets sent to the server, I found that the access_token being sent is the one that was originally issued. I tried called `getTokenResponse` before calling `getUserInfo`, but with no luck.

Digging a bit deeper I discovered that credentials are being read from local storage (`openid_client:auth`). However `openid_client:auth` is only updated when calling `authorize`, which, following your examples, I do not if I already have credentials.

The only way I found that this works<sup>1</sup> is if I call `getTokenResponse(true)`, forcing a token refresh. However, my assumption was that expired access tokens should cause a refresh automatically?
Any feedback would be highly appreciated.

1: It does not actually work due to another bug I have encountered, but I'm still investigating. It's most likely due to my setup, but will open a separate issue if otherwise

**Comment by ntoljic** [comment]
After a fresh look today, I finally understand what is going on.
The web implementation only supports `implicit flow`, which does **not** return a `refresh_token`. Thus, calling `getTokenResponse(true)` results in an error (`Expected a value of type 'String', but got one of type 'Null'`) when the function attempts to create the refresh request.

Looking through the other issues I found https://github.com/appsup-dart/openid_client/issues/19#issuecomment-759443834, however changing the setting `Use Refresh Tokens For Client Credentials Grant` does not change the server response.

My conclusion therefore is, that the automatic refresh is currently not supported for browser apps.

**Comment by rbellens** [comment]
The `implicit flow` indeed does not return a `refresh_token`. In this case, you should rely on a different method to get a new token. Typically, a hidden iframe can be used for this. A sample implementation of this can now be found in the `openid_client_browser.dart` `Authenticator` class.
