### ISSUE TITLE
Web app returns empty credentials and userInfo

### ISSUE THREAD

**Issue by reichherzerp** [appsup-dart/openid_client#42]
With the example for a Flutter app on Android, I am redirected to the login entry without any problems and have access to my userInfo data after entering my user data. However, if I replace the authenticate() function with the code provided in the readme for the web version, I am redirected correctly, but I always get null for authenticator.credential. After coming back from the login screen to the webapp, there is a url displayed shortly that contains the access_token, the state, and the id_token. But within a second, this url is replaced by my default local host address without any parameters appended. The webapp gets also reloaded. I don't see what is missing for the web version, as it works for Android as expected. I would appreciate your help.

During debuggin, I have noticed that the function _credentialFromUri(Flow flow) only sees the basic local host address.

For reproducing the problem, here is a minimal working example. I use auth0 for login and allowed redirecting to the local host, which is used for Android and the web version. The plus button starts the redirection:

```
import 'package:flutter/material.dart';
// import the browser version
import 'package:openid_client/openid_client_browser.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() async {
    var userInfo = await authenticate(
        Uri.parse('https://TEST.eu.auth0.com'),
        'CLIENT_ID',
        ['openid', 'profile', 'offline_access']);
    print('userInfo: $userInfo');
    _counter++;
  }

  authenticate(Uri uri, String clientId, List<String> scopes) async {
    // create the client
    var issuer = await Issuer.discover(uri);
    var client = new Client(issuer, clientId);

    // create an authenticator
    var authenticator = new Authenticator(client, scopes: scopes);

    // get the credential
    var c = await authenticator.credential;

    if (c == null) {
      // starts the authentication
      authenticator.authorize(); // this will redirect the browser
    } else {
      // return the user info
      return await c.getUserInfo();
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('test'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

Flutter doctor :
```
[✓] Flutter (Channel stable, 2.0.5, on Linux, locale de_DE.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] Connected device (1 available)
```

**Comment by Miles-Ahead-Digital** [comment]
@rbellens 

I get the same error with the coding above.
The  authenticator.authorize() command reloads the complete app and the authenticator object (and the credential object) is null.

The id_token and the access_token are issued the first time after Login.
From the second time on no login is necessary and the tokens are refreshed or reissued once the browser reloads the app.

Please advise how we get this problem solved.

Best regards
Stefan

![CleanShot 2021-06-21 at 10 50 00](https://user-images.githubusercontent.com/58099738/122734903-cbb0b580-d27e-11eb-9e15-9104051e5484.gif)

**Comment by sguesdon** [comment]
the problem is that flutter rewrite the hash before the library can read it.

not having found how to intercept the initial hash through flutter so i added javascript at startup to intercept the original hash and register the information in the local storage.

```js
// web/js/keycloak-adapter.js
if(window.location.hash) {
  const params = {};
  const requiredParams = ['access_token', 'code', 'id_token'];
  const rawParams = (window.location.hash.substr(1)).split("&");
  for(rawParam of rawParams) {
    const [key, value] = rawParam.split('=');
    params[key] = value;
  }
  if(requiredParams.some((k) => typeof params[k] != 'undefined')) {
    window.localStorage['openid_client:auth'] = JSON.stringify(params);
  }
}
```

Is there a simpler, cleaner solution to solve the problem?

**Comment by samisa-abeysinghe** [comment]
Is there a suggested solution for this? Running into the same issue and looking into a fix.

**Comment by rbellens** [comment]
You need to capture the url before calling flutter's `runApp` in the main method. See https://github.com/appsup-dart/openid_client/blob/c89d11b172c842bf13f5ce47632de20012eddd1d/example/flutter_example/lib/main.dart#L26 for an example.

**Comment by SpatariuRares** [comment]
I have this problem in the flutter example I change only the url and the client id, how I can resolve? 
is possible the problem in on the keycloack configuration?

**Comment by alex27riva** [comment]
> You need to capture the url before calling flutter's `runApp` in the main method. See
> 
> https://github.com/appsup-dart/openid_client/blob/c89d11b172c842bf13f5ce47632de20012eddd1d/example/flutter_example/lib/main.dart#L24-L28
> for an example.

Hi, where is defined the `getRedirectResult()` function?
