### ISSUE TITLE
Authorization code with PKCE for Flutter Web

### ISSUE THREAD

**Issue by nerdy-plutonian-ng** [appsup-dart/openid_client#43]
After entering credentials on the Identity server login page, i am redirected to my app with a similar url

http://localhost:50360/?code=7EF098B90CC6CAC7D19AFB3997231A026537A1AC805C5D033CFE9EC013A89517&scope=openid%20profile%20email%20api%20offline_access&state=ccEhlq8gNfkNeHwPqprJPNSwQfpDXiDv5cmjxRf5CGKFrCMcu9&session_state=1IXEnvob9q9QlWp-NuvMLZ7tG-qFQvfL8ZXdO7m-30A.3BE01EA2152E278E7A269B53B88FECB2

How do i get an access token and refresh?

**Comment by jasonlaw** [comment]
@nerdy-plutonian-ng , had you solved your problem?

**Comment by nerdy-plutonian-ng** [comment]
@jasonlaw no I have not

**Comment by jasonlaw** [comment]
I managed to solve it by referring to this [discussion](https://github.com/MaikuB/flutter_appauth/issues/70) thread.
In summary, 
1. Add a callback.html in the web folder.
2. Set your redirect uri to the callback.html.
3. Add processOAuth method before the runApp.
4. In the processOAuth, you may parse the query parameters from your identity server.

**Comment by anushkavidanage** [comment]
@jasonlaw Do you have a working solution anywhere that we can refer to? Been struggling with this for a while.

**Comment by jasonlaw** [comment]
> @jasonlaw Do you have a working solution anywhere that we can refer to? Been struggling with this for a while.

https://github.com/jasonlaw/aether_passport

**Comment by rbellens** [comment]
I think this should be solved with PR #62 . Will be included in version 0.4.7

**Comment by adrian-moisa** [comment]
For anyone interested to implement authorisation flow on the web. It appears the readme provides a sample for android/ios. Currently the `Authenticator` that `openid_client` provides for the browser supports only the implicit flow as far as I can see from the source code. I'm trying to figure out if I can write my own Authenticator that can support authorisation flow on the web. I was hopping to find this as part of the library. No clear docs/reason are provided as to why implicit flow is used on the web as long as it is currently deprecated and advised against.
