### ISSUE TITLE
Keycloak Issue using Google Provider (403 error and browser not closing)

### ISSUE THREAD

**Issue by SylvainAssemat** [appsup-dart/openid_client#46]
Hi all

Just found an issue using Keycloak, when user try to authenticate using the Google Provider (on keycloak UI authentication page)
First issue : 403 disallowed user agent
 FIX : => i was forced to comment this line ```forceWebView: true,```

Now next issue is that opening a native browser (and not in-app browser), the browser can't be closed after authentication 
The redirect_uri keep showing (with a blank page)
I can not found out how to fix this 
Of course the ``` await closeWebView();``` can't help when not in an in-app webview.

Any clue or same use case maybe ?

Maybe a way to fix the 403 error using url_lancher without disallowing the in-app webview ?

Thanks

**Comment by KamilKlecha95** [comment]
I am facing same Issue. Google nows has forbidden authenticating in embedded WebView. The only solution is to open browser, but after successfully authenticating, browser is not closing. Anyone ?

**Comment by rbellens** [comment]
This seems to be an issue with how to open and handle in app web views and how to redirect back to the app. There are several flutter plugins for doing this stuff, but this is not part of this library. There are however some examples in the readme and the examples folder.

When you cannot use an in-app webview and therefore cannot close the browser window, you probably need to use a redirect url that redirects to the app. In that case, you'll need to capture the response and call the `Flow.callback` method explicitly. You could use the `uni_links` package or similar for this.
