### ISSUE TITLE
Using a custom redirectUri instead of "http://localhost:$port" is not working

### ISSUE THREAD

**Issue by mrahhal** [appsup-dart/openid_client#5]
In this issue, this comment concludes the same: https://github.com/appsup-dart/openid_client/issues/4#issuecomment-449391146

I spent so much time debugging this, and finally had to change my custom redirectUri from my openid Identity Server to match `http://localhost:$port`. Anything other than that didn't work. The browser would just display "Can't open this url. Unknown..." and the app would hang there.

I tried debugging but can't make out why this happens with a custom redirectUri only.

**Comment by jtammaro** [comment]
+1

**Comment by dieos2** [comment]
Eu não consigo fazer o identity me retornar para o aplicativo após o login, diz que a url não existe.

**Comment by kentcb** [comment]
The code seems to hard-code `http://localhost` as the redirect URL. See [here](https://github.com/appsup-dart/openid_client/blob/master/lib/src/openid.dart#L252).

**Comment by jhancock4d** [comment]
It needs to either allow an arbitrary URL and detect it (appears you can add whatever URL you want, but it ignores the response code) or allow https on local host

**Comment by tienthai0205** [comment]
Any fix for this issue?

**Comment by tienthai0205** [comment]
> It needs to either allow an arbitrary URL and detect it (appears you can add whatever URL you want, but it ignores the response code) or allow https on local host

which part of the code shows that it ignores the response when using custom uri?

**Comment by jesusmunozmobivery** [comment]
Any update of this issue?

I have the same error in Flutter 2.2.3 (stable) and openid_client 0.4.1

**Comment by suniastar** [comment]
I found a workaroud for this problem with android apps mentioned in #4.
