### ISSUE TITLE
How to delete auto login

### ISSUE THREAD

**Issue by xmartinez22** [appsup-dart/openid_client#50]
In flutter, the system automatically logs in if there is a 'state' available i'm assuming. Problem being is that the token may not be valid and i keep getting unauthorized over and over. How can i remove this auto login or clear the state / token?

**Comment by elham-rababah** [comment]
any update on this

**Comment by rbellens** [comment]
This package does not keep any state, except when using the `Authenticator` for web (so, when importing `openid_client_browser.dart`). The openid provider might keep some state in the browser. This could maybe be cleared by using the `end_session_endpoint`. You can do this by opening the url generated with `credential.generateLogoutUrl` or use the `issuer.metadata.endSessionEndpoint`. 
Alternatively, you could try to open the auth url in a browser without using storage. E.g., with the `url_launcher` package you can set `enableDomStorage` to false in `WebViewConfiguration`.
