### ISSUE TITLE
Not able to get refresh token for the web 

### ISSUE THREAD

**Issue by SameerChorge94** [appsup-dart/openid_client#52]
**Description:**

i'm trying to get the access token using the below function as per the readme docs 
`var tr = await credential.getTokenResponse()`

when i fetch the token as per the above method then getting the token, but when i fetch the token with below syntax i.e send the dorceRefresh argument to true then getting below error
Called Function:
`var tr = await credential.getTokenResponse(true)`

Error:
`Invalid Argument : null `

Can you suggest any workaround for this, as per our requirement we need to get the latest token by forceRefresh option.
also can you suggest correct way for sending that forceRefresh option, As per the package code checked there that forceRefresh argument is provided in the square braces [ ] so that's why while calling that function its not suggesting that option for sending argument.
`Future<TokenResponse> getTokenResponse([bool forceRefresh = false])`

**Comment by SameerChorge94** [comment]
Any update on this issue?   is there any solution or workaround for refreshing token in web or by using any other flow instead of implicit flow?

**Comment by anushkavidanage** [comment]
I have the same issue. I think the problem is with capturing the redirect URI. As far as I understand the library is not able to capture the redirect URI. Have you been able to get around this?
