### ISSUE TITLE
Issuer.discover(uri)  return XMLHttpRequest error in response -  Flutter on web

### ISSUE THREAD

**Issue by ShrinivasChiliveri** [appsup-dart/openid_client#53]
Issuer.discover(uri) return the error in response saying "XMLHttpRequest error". I am using this package for Flutter on web for chrome browser. I can't proceed further. It seems it is getting on http.get request.  Can you let me know how to resolve this error. I can see the configuration file in response when I run URL directly on chrome.

Is this package works for Flutter on web?

**Comment by keinou** [comment]
`var issuer = await Issuer.discover(Uri.parse(
        "https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration"));
    var client = new Client(issuer, clientId);`

**Comment by rbellens** [comment]
The `.well-known/openid-configuration` postfix is added by the library, so you should not add it yourself. This should work:

```
var issuer = await Issuer.discover(Uri.parse("https://login.microsoftonline.com/common/v2.0/"));
```
