### ISSUE TITLE
Before get the user info need to get code and codeVerifier and add to mobile api to get info

### ISSUE THREAD

**Issue by nandynandhini2805** [appsup-dart/openid_client#54]
I have to create an app as medical, On the login page, I have the continue with NHS login button, while clicking on it...it should redirect to mobile web view and enter the login credentials it redirects to the application dashboard page. I try to use this library, not able to use it can you please help me!

**Comment by rbellens** [comment]
Sorry for the late answer. This issue contains a bit too little information and since it is an old report, I will close it. If you still have a problem, please open a new issue with some more information.
