### ISSUE TITLE
Allow specifying the flow using Authenticator

### ISSUE THREAD

**Issue by Andreas02-dev** [appsup-dart/openid_client#55]
Hi Rik,

When using the `Authenticator` class and providing a `redirectUri`, the Authorization Code grant type will be chosen by default. In my case, a different redirectUri is needed, together with the Authorization Code with PKCE grant type.

As shown in PR #41 , it has already been attempted to expose the flow constructor for customization, however I do not see this present in the main branch.

My proposal is to add an optional `Flow` in the `Authenticator constructor`, which will default to the current implementation when not given. This way, current implementations of the library will continue to be supported, while enabling both `redirectUri` and `Authorization Code with PKCE` grant types to be used simultaneously when necessary.

I have implemented the proposed change and will open and link a PR for you to review and merge.

**Edit: The corresponding PR is**  #56.

Please let me know if there are any questions and whether the proposed change is acceptable.

Looking forward to hearing from you and with kind regards,

Andreas

**Comment by rbellens** [comment]
This is solved in version 0.4.4
