### ISSUE TITLE
Add support for grant_type password

### ISSUE THREAD

**Issue by davidpanic** [appsup-dart/openid_client#57]
Keycloak provides OpenID Connect logins with username and password.

The endpoint is POST `https://<keycloak-domain:port>/auth/realms/<realm_name>/protocol/openid-connect/token`
With the x-www-form-urlencoded body:
`username=xyz&password=abc&grant_type=password&client_id=our_client_id`

This works If I send the request directly to the server, but I cannot for the life of me figure out how to do it with this library. All I could find by looking at the source is that you support grant_type `authorization_code` and `urn:ietf:params:oauth:grant-type:jwt-bearer` but not `password`.

**Comment by rbellens** [comment]
Hi @davidpanic ,

This is now supported. Will be released soon.
