### ISSUE TITLE
Throw exception with error name if error_description is not provided 

### ISSUE THREAD

**Issue by AhmedMozaly** [appsup-dart/openid_client#6]
currently, only error_description is used to get the error message returned from token endpoint
there are cases where server just return error without error_description, so:
* json["error_description"] should be used if exists 
* json["error"] should be used if error_description not exists 

![image](https://user-images.githubusercontent.com/781863/53277568-28325300-370d-11e9-8d8b-d5b8611f45cb.png)

**Comment by rbellens** [comment]
as of version 0.2.5, there is a `OpenIdException` class containing both the error code and the description.
