### ISSUE TITLE
openid_client v 0.4.6 depends on url_launcher v 5.2.7 which isn't null-safe

### ISSUE THREAD

**Issue by AsmaaM93** [appsup-dart/openid_client#61]
openid_client v 0.4.6 depends on url_launcher v 5.2.7 which isn't null-safe which makes it not null-safe per say

**Comment by rbellens** [comment]
`openid_client` does not have a dependency on `url_launcher`. `openid_client` is a package that runs in both a `dart` and `flutter` environment. `url_launcher` is a flutter plugin. A dependency on `url_launcher` would make `openid_client` flutter only. Probably, you have some other dependency.
