### ISSUE TITLE
API Access

### ISSUE THREAD

**Issue by milosjovac** [appsup-dart/openid_client#7]
Hi,

I was able to use openid_client library in Flutter to successfully login and get user information with `getUserInfo`, but I'm not sure how to proceed and access secure endpoints on my server. All endpoints expect valid access_token as a part of the `Authorization` header. Can I access this endpoints using openid_client directly, or do I have to somehow get access_token from the library? Additionally would openid_client take care of refreshing the access_token for me?

Thanks,
Milos

**Comment by rbellens** [comment]
As of version 0.2.5, you can get the access token as follows

```dart
var token = await credential.getTokenResponse();
var accessToken = token.accessToken;
```

Or, create a http client that adds the authorization header as follows:

```dart
credential.createHttpClient();
```

**Comment by SunilJamkatel** [comment]
create a variable for additionalParaments:
```
Map<String, String> _additionalParameters = {
    'audience': 'your-api-audience',
  };
```
and pass this to the `AuthorizationTokenRequest` like this:

```
AuthorizationTokenRequest(_clientId, _redirectUrl,
            serviceConfiguration: _serviceConfiguration,
            scopes: _scopes,
            additionalParameters: _additionalParameters),
```

this will generate a jwt token for accesstoken which can be passed in the `Authorization` header as bearer token to be used by your api.

Hope this helps!
