### ISSUE TITLE
_randomString is not using it's length parameter

### ISSUE THREAD

**Issue by wferem1** [appsup-dart/openid_client#72]
in `lib/src/openid.dart` the method `_randomString` is not using the `length` parameter, but will always return with a String of length 50.

```dart
String _randomString(int length) {
  var r = Random.secure();
  var chars = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
  return Iterable.generate(50, (_) => chars[r.nextInt(chars.length)]).join();
}
```

**Comment by rbellens** [comment]
Hi @wferem1 ,
This is fixed in commit 850acc961347436c4f5a2fc6828b5a926b51423d.
I will release a new version containing this fix soon.
