### ISSUE TITLE
Does not "stay connected" after killing app

### ISSUE THREAD

**Issue by GaelleJoubert** [appsup-dart/openid_client#81]
Hello, I am seeing a weird behavior, and I am wondering if it is an expected behavior or not.
I am having the issue with my code, but I have been able to reproduce it with the exemple code as well.

Here is what happen (with the exemple app) :
1- Click on Login => being redirect to the login page
2- Enter your credentials => you are logged
3- If you click on 'Logout', then 'Login' again, you are automatically logged again, no need to enter your credentials.

BUT

if you you do step (1) & (2), and then :
(3bis) Kill the app, when you open the app, and click on 'login', **you are not automatically login again !**
I would have expected the same behaviour for (3bis) than for step (3).

Because it means that each time you kill the app, you have to log again .. not very convenient !

Is it the expected behavior ? Is there any way to avoid having to enter your credential after the app is killed ?

Ps: I know this is not an "access token validity" err, because my Access Token is valid long enough, and it works with other libraries I've tried.

Thanks for your help.

**Comment by sircuri** [comment]
I don't think this has anything to do with this library. There is no way for a library to maintain state between application runs. You have to implement some sort of state yourself. The token only exists in memory. That's why you are logged in again after pressing the login button.

**Comment by rbellens** [comment]
This package doesn't handle storage of credentials. You should store and restore the credentials in your own code.
