### ISSUE TITLE
Credentials.revoke() throws an exception. 

### ISSUE THREAD

**Issue by npodbielski** [appsup-dart/openid_client#83]
Calling:

`credentials.revoke();`

does not work with Gitlab OmniAuth provider. 
It returns an error 'Unauthorized'.

I did debug it and it looks like `revoke` method is calling endpoint with `Authorization: Bearer access_token` which does not work because you cannot revoke refresh token with access token. This should be basic auth with `clientId:clientSecret` value. 

I did wrote something like that:

```
var token = await userInfo?.credentials.getTokenResponse();

    var body2 = {
      'token': token?.refreshToken!,
      'token_type_hint': 'refresh_token'
    };

    var auth = base64.encode(
        ('efb531c6f1d2d46db566135b95dcce7ef994936d1bc2b9b92971c56439da14ds1' +
                ':' +
                'a380c5a17995f3d9011e6a9d9722b8778913872daaae19965b9f39e7f6as43f2')
            .codeUnits);

    var response = await http.Client().post(issuer.metadata.revocationEndpoint!,
        body: body2, headers: {'Authorization': 'Basic ${(auth)}'});
```

and it works, token is destroyed on GitLab side. 
What is the usage of `revoke`? Why it does not work for me? Did I misconfigured something? 
To me it looks like oversight, all endpoints calls tries to authorize with access_token. However revoking should be treated  differently.

**Comment by rbellens** [comment]
should be fixed in version `0.4.8`
