### ISSUE TITLE
Authenticator not override Flow.authorizationCodeWithPKCE scopes

### ISSUE THREAD

**Issue by vincenzomartusciello** [appsup-dart/openid_client#85]
Hello, i'm having a problem.
Currently the `Flow.authorizationCodeWithPKCE` method accepts a list of scopes, however the `Authenticator` constructor does not override the list but adds.
In that case, like mine, where the app doesn't need the default scopes, apart from openid, I'm forced to manually modify the library to make it useable.
Is the behavior intended?

**Comment by ilmalte** [comment]
This issue affects the method `Flow.authorizationCode` as well because the `Authenticator` constructor is the same.

**Comment by rbellens** [comment]
The `Authenticator` class is merely a wrapper around `Flow` that facilitates some things. It might not cover all use cases, but it would be relatively easy to implement your own version. It also has a `Authenticator.fromFlow` constructor that allows you to pass a flow with other scopes.
