### ISSUE TITLE
redirect url?

### ISSUE THREAD

**Issue by RaitonGG** [appsup-dart/openid_client#89]
once i enter the provider login webview, it throws an error saying that i didn't whitelist the redirect url.
what's the redirect url of the app so i can white list it?

**Comment by mahendravijay** [comment]
Same error.

**Comment by galsilb** [comment]
Its:
http://localhost:4000/

**Comment by mahendravijay** [comment]
> Its: http://localhost:4000/

Worked for me.

**Comment by rbellens** [comment]
In the example flutter app, http://localhost:4000/ is used, but off course you can choose another in your app.
