### ISSUE TITLE
How does openid_client compare to openidconnect_flutter?

### ISSUE THREAD

**Issue by adrian-moisa** [appsup-dart/openid_client#98]
Hello dear maintainers! I've been doing for the past 2 weeks a lot of research to get up to speed with Oauth2 and OIDC in Flutter. I've looked at around 10 different libs including this one. So far the only contenders that are left on my list are [openidconnect_flutter](https://github.com/4D-Technologies/openidconnect_flutter) and [openid_client](https://github.com/appsup-dart/openid_client). Both seem to be quite focused on OIDC and I'm very interested in this protocol. I've looked at the source code in both of them and I can see some diferences in approach. Tough I don't have quite a well trained eyed in matters of auth. I'd like to receive your guidance and advice regarding reasons I should chose openid_client. Any advice will be much appreciated.

Myself I'm interested in implementing an OIDC authorization flow for multiple platforms, with the expectation that in the near future I will be implementing social login and potentially even including a 3rd party extensions marketplace where other devs can register extensions in the platform that I'm building. Hope to hear some feedback from you. Regards!

**Comment by rbellens** [comment]
Not sure what is your exact question. I don't know `openidconnect_flutter` very well, so I can't really compare. I guess, as that is a flutter package, it can only be used in flutter apps, whereas `openid_client` can be used in any dart environment (flutter, web, cli, backend).

**Comment by adrian-moisa** [comment]
After more digging I concluded that`openid_client` is the one I should use mostly because it supports PKCE. In comparison to `openidconnect_flutter` I see that `openid_client` has far better traction.
