### ISSUE TITLE
Having trouble with the CLI, zsh does not find openid_client

### ISSUE THREAD

**Issue by adrian-moisa** [appsup-dart/openid_client#99]
```zsh
openid_client issuers list
zsh: command not found: openid_client
```

I even tried adding it to the PATH, no change.
`export PATH=~/.pub-cache/hosted/pub.dev/openid_client-0.4.7/bin/:$PATH`

Any advice? And question, do I actually need the cli? It's unclear from the readme if the commands are optional or mandatory. Thank you!

**Comment by rbellens** [comment]
Did you install the cli with the command `dart pub global activate openid_client`?

The cli can be helpful to test things (checkout an issuer, try to auth, ...), but probably you do not need it.

**Comment by adrian-moisa** [comment]
Thank you for the feedback. I managed to implement everything without using the cli.
